#!/bin/bash
#For example:
#./check_csv_dumps.sh secrets/graphs/fff6079024e5943c2e9a4f049ef235f4307ed1bd/ 
#compares CSV files generated by fff6079024e5943c2e9a4f049ef235f4307ed1bd to latest commit

echo "Remember that some files are randomised"
diff  <(find ${1}/ -name '*.csv' -printf '"%p"\n' | sed 's#secrets/graphs/[^/]*/*##') <(find secrets/graphs/`git rev-parse HEAD`/ -name '*.csv' -printf '"%p"\n' | sed 's#secrets/graphs/[^/]*/*##') || { echo "Misalignment" 2>&1; exit 1; }
paste <(find ${1}/ -name '*.csv' -printf '"%p"\n')                                    <(find secrets/graphs/`git rev-parse HEAD`/ -name '*.csv' -printf '"%p"\n') | sed 's/.*/diff -qs &/' | sh #| grep -v '_r[[:digit:]].csv differ$'
